### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by translate-h5p**
Translations update from [Weblate](https://translate-h5p.tk/weblate/projects/h5p/h5p-dictation/) for H5P/h5p-dictation.

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by otacke — CHANGES_REQUESTED** [review]
There are lots of empty fields. Those need to keep the English original if there's not translation available yet.

**Comment by otacke** [comment]
@translate-h5p There are still plenty of fields containing empty strings (those should be replaced by the corresponding English strings). I could, of course, cherry pick and fix everything manually, but I think this should be fixed on weblate's end.

**Comment by sr258** [comment]
I‘ll simply delete the whole file with missing translations

**Review by otacke — APPROVED** [review]
Excellent!

**Pull request merged**
